{ lib, pkgs, config, inputs, ... }:

{
  options.services.tiny-dfr.enable = lib.mkEnableOption "tiny-dfr";

  config = lib.mkIf config.services.tiny-dfr.enable (let
    tiny-dfr = pkgs.callPackage ./package.nix { inherit pkgs inputs; };
  in {
    environment.systemPackages = [ tiny-dfr ];
    systemd.packages = [ tiny-dfr ];
    services.udev.packages = [ tiny-dfr ];

    environment.etc."tiny-dfr/screenshot.svg".text = ''
       <svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 0 122.88 117.52" width="48">
       <path
         fill="white"
         d="M74.01,0v11.98H19.13c-3.93,0.01-7.14,3.22-7.15,7.15v17.74H0V19.13c0-1.07,0.09-2.09,0.26-3.14
           c0.91-5.37,3.99-10,8.56-12.96c3.13-2,6.6-3.01,10.31-3.03H74.01L74.01,0z
           M106.86,101.52v16H94.87v-16H79.6V89.53h15.27V69.72
           h11.98v19.81h16.03v11.98H106.86L106.86,101.52z
           M0,48.85h11.98v33.53c0.01,2.69,1.52,5.12,3.9,6.36L10.4,99.4
           c-3.97-2.06-7.06-5.36-8.84-9.46C0.52,87.51,0.01,85.02,0,82.39V48.85L0,48.85z
           M24.89,101.52V89.53h42.73v11.98H24.89
           L24.89,101.52z
           M106.85,57.74H94.87V19.13c-0.01-3.93-3.22-7.14-7.15-7.15h-1.73V0h1.73c1.07,0,2.09,0.09,3.14,0.26
           c5.37,0.91,10,3.99,12.96,8.56c2,3.13,3.01,6.6,3.03,10.31V57.74L106.85,57.74z"
       />
       </svg>
    '';

    environment.etc."tiny-dfr/config.toml".text = ''
      # tiny-dfr config template. Do not edit this file directly, instead
      # copy it to /etc/tiny-dfr/config.toml and edit that copy.
      # The daemon will merge those two files, giving preference to the one in /etc
      
      # F{number} keys are shown when Fn is not pressed by default.
      # Set this to true if you want the media keys to be shown without Fn pressed
      MediaLayerDefault = true
      
      # Set this to false if you want to hide the button outline,
      # leaving only the text/logo
      ShowButtonOutlines = false
      
      # Set this to true to slowly shift the entire screen contents.
      # In theory this helps with screen longevity, but macos does not bother doint it
      # Disabling ShowButtonOutlines will make this effect less noticeable to the eye
      EnablePixelShift = false
      
      # Set this to the fontconfig pattern to be used to pick a font for text labels
      # Some examples are:
      # "" - default regular sans-serif font
      # ":bold" - default bold sans-serif font
      # For full reference on accepted values see the fontconfig user guide,
      # section "Font Names"
      # https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
      FontTemplate = ":bold"

      AdaptiveBrightness = false
      ActiveBrightness = 1
      
      # This key defines the contents of the primary layer
      # (the one with F{number} keys)
      # You can change the individual buttons, add, or remove them
      # Any number of keys that is greater than 0 is allowed
      # however rendering will start to break around 24 keys
      PrimaryLayerKeys = [
          # Action defines the key code to send when the button is pressed
          # Text defines the button label
          # Svg specifies the icon to be used for the button.
          # Do not include the .svg extension in the file name.
          # Svgs are looked up in /etc/tiny-dfr first and then in /usr/share/tiny-dfr
          # Only one of Text or Svg is allowed,
          # if both are present, the behavior is undefined.
          # For the list of supported key codes see
          # https://docs.rs/input-linux/latest/input_linux/enum.Key.html
          { Text = "F1",    Action = "F1"    },
          { Text = "F2",    Action = "F2"    },
          { Text = "F3",    Action = "F3"    },
          { Text = "F4",    Action = "F4"    },
          { Text = "F5",    Action = "F5"    },
          { Text = "F6",    Action = "F6"    },
          { Text = "F7",    Action = "F7"    },
          { Text = "F8",    Action = "F8"    },
          { Text = "F9",    Action = "F9"    },
          { Text = "F10",   Action = "F10"   },
          { Text = "F11",   Action = "F11"   },
          { Text = "F12",   Action = "F12"   },
          { Text = "SysRq", Action = "Sysrq" }
      ]
      
      # This key defines the contents of the media key layer
      MediaLayerKeys = [
          { Svg = "brightness_low",  Action = "BrightnessDown"      },
          { Svg = "brightness_high", Action = "BrightnessUp"        },
          { Svg = "mic_off",         Action = "MicMute"             },
          { Svg = "search",          Action = "Search"              },
          { Svg = "backlight_low",   Action = "IllumDown"           },
          { Svg = "backlight_high",  Action = "IllumUp"             },
          { Svg = "fast_rewind",     Action = "PreviousSong"        },
          { Svg = "play_pause",      Action = "PlayPause"           },
          { Svg = "fast_forward",    Action = "NextSong"            },
          { Svg = "volume_off",      Action = "Mute"                },
          { Svg = "volume_down",     Action = "VolumeDown"          },
          { Svg = "volume_up",       Action = "VolumeUp"            },
          { Svg = "screenshot",      Action = "SelectiveScreenshot" }
      ]
      '';
  });
}
